# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_username: quinnmcnamara
  sign_up_access_code: intro
  admin_email: sudheerm16@gmail.com
  admin_first_name: Quinn
  admin_last_name: Alexander
  admin_password: Virginia9567
  secret_key_base: 00b818770c7cb6a300eb25923d0d4d0e9eca730ff9f356804138bc4683316847bce0cbc8982678b30ab2c5b9a38ff99bbad12c0f35e8fea73bb5fb75a0f194a9
  google_map_api_url: https://maps.googleapis.com/maps/api/js?key=
  google_api_key: AIzaSyCGAr2rvexGfvwFAv87x-TwJtDLDkkXBcI
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://89c47584.ngrok.io

test:
  secret_key_base: 43babf584eadb1d01708822826b4d604dd960b37c57109dfe0b1ec751c786d954b5ee73ae56e45f26f63e4d28a0512f2eb7f82cd285657fe0200e9007588a01e

staging:
  admin_username: <%= ENV["admin_username"] %>
  admin_email: <%= ENV["admin_email"] %>
  admin_first_name: <%= ENV["admin_first_name"] %>
  admin_last_name: <%= ENV["admin_last_name"] %>
  admin_password: <%= ENV["admin_password"] %>
  secret_key_base: 6339701b62270430a321f028400c20ca102410970e8a91791f3b1d188536951b605fd1026cd9e8c54d7ea6e809c0a2f3a0c6a43cb6bd82745d9707e00a32022f
  google_map_api_url: https://maps.googleapis.com/maps/api/js?key=
  google_api_key: AIzaSyCGAr2rvexGfvwFAv87x-TwJtDLDkkXBcI
  paypal_host: https://www.sandbox.paypal.com
  app_host: <%= ENV["secure_domain"] %>
  sign_up_access_code: intro
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  paypal_host: https://www.paypal.com
  secret_key_base: 6339701b62270430a321f028400c20ca102410970e8a91791f3b1d188536951b605fd1026cd9e8c54d7ea6e809c0a2f3a0c6a43cb6bd82745d9707e00a32022f
  admin_username: <%= ENV["admin_username"] %>
  admin_email: <%= ENV["admin_email"] %>
  admin_first_name: <%= ENV["admin_first_name"] %>
  admin_last_name: <%= ENV["admin_last_name"] %>
  admin_password: <%= ENV["admin_password"] %>
  secret_key_base: 6339701b62270430a321f028400c20ca102410970e8a91791f3b1d188536951b605fd1026cd9e8c54d7ea6e809c0a2f3a0c6a43cb6bd82745d9707e00a32022f
  google_map_api_url: https://maps.googleapis.com/maps/api/js?key=
  google_api_key: AIzaSyCGAr2rvexGfvwFAv87x-TwJtDLDkkXBcI
  app_host: <%= ENV["secure_domain"] %>
  sign_up_access_code: intro
